# -- mode: ruby --
# vi: set ft=ruby :
require 'yaml'
yaml = YAML.load_file("machines.yml")

K8S_IP="192.168.66.20"
K8S_VERSION="1.14.9-00"
MYSQL_PASSWORD='teste@teixeira'

Vagrant.configure("2") do |config|
  yaml.each do |server|
    config.vm.define server["name"] do |srv|
      srv.vm.box = server["sistema"]
      srv.vm.network "private_network", ip: server["ip"]
      srv.vm.hostname = server["hostname"]
      srv.vm.provider "virtualbox" do |vb|
        vb.name = server["name"]
        vb.memory = server["memory"]
        vb.cpus = server["cpus"]
      end

config.vm.provision "shell", inline: <<-SHELL

apt-get update
apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common


if [ $HOSTNAME = "srv-gitlab" ]; then
  echo ==== Installing Requirements ==============================================
  sudo apt-get install openjdk-8-jdk-headless -y
  sudo apt-get install -y curl openssh-server ca-certificates

  echo ==== Installing GitLab CE =================================================
  curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
  sudo apt-get install -y gitlab-ce
  sudo gitlab-ctl reconfigure
  sudo gitlab-ctl status

  echo ==== Installing GitLab Multi Runner =======================================
  curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | sudo bash
  sudo apt-get install -y gitlab-ci-multi-runner

fi;

if [ $HOSTNAME = "srv-orchestrator" ]; then

 curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
 add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 apt-get update -y
 curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
 systemctl start docker
 systemctl enable docker

 curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
 echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list
 apt-get update -y
 apt-get install -y kubeadm=#{K8S_VERSION} kubelet=#{K8S_VERSION} kubectl=#{K8S_VERSION}  kubernetes-cni=0.7.5-00

 swapoff -a

 echo "KUBELET_EXTRA_ARGS='--node-ip=#{K8S_IP}'" > /etc/default/kubelet
 kubeadm init --apiserver-advertise-address "#{K8S_IP}" --pod-network-cidr=10.244.0.0/16
 mkdir $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
 kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
 kubectl taint nodes --all node-role.kubernetes.io/master
 curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
 kubectl taint nodes --all node-role.kubernetes.io/master-
 kubectl cluster-info

fi;

 apt-get update -y

  SHELL

  end

 end

end
